#include <QByteArray>

#include "parser.h"
#include "3rdparty/md4c/src/md4c-html.h"


/* Global options. */
static unsigned parser_flags = 0;


void captureHtmlFragment (const MD_CHAR* data, MD_SIZE data_size, void* userData) {
    QByteArray* array = static_cast<QByteArray*>(userData);

    if (data_size > 0) {
        array->append(data, data_size);
    }
}

QString Parser::Parse(const QString &markdown, const int &dia)
{
    if (dia == GitHub)
        parser_flags |= MD_DIALECT_GITHUB;
    else
        parser_flags |= MD_DIALECT_COMMONMARK;

    const QByteArray array = markdown.toLocal8Bit();
    QByteArray out;

    /* Write down the document in the HTML format. */
    out.append("<!DOCTYPE html>\n");
    out.append("<html>\n");
    out.append("<head>\n");
    out.append("<title>HTML generated by md4c</title>\n");
    out.append("<meta name=\"generator\" content=\"md2html\">\n");
    out.append("</head>\n");
    out.append("<body>\n");

    md_html(array.data(), (MD_SIZE)array.size(), &captureHtmlFragment, &out,
            parser_flags, MD_HTML_FLAG_DEBUG | MD_HTML_FLAG_SKIP_UTF8_BOM);

    out.append("</body>\n");
    out.append("</html>\n");

    return out;
}
