name: 'Build'

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Linux:   https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/
        # macOS:   https://download.qt.io/online/qtsdkrepository/mac_x64/desktop/
        qt-version: ['5.12.8', '6.4.1']
        experimental: [false]
    steps:
    - uses: actions/checkout@v4

    # https://github.com/marketplace/actions/install-qt
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt-version }}
        cache: true
        cache-key-prefix: ${{ runner.os }}-QtCache-${{ matrix.qt-version }}

      #
      # Clone dependencys
      #
    - name: Clone MarkdownEdit's dependencys
      run: |
        git submodule update --init --recursive -j 4

      #
      # Build MarkdownEdit using CMake
      #
    - name: Build MarkdownEdit using CMake
      run: |
        mkdir build-cmake && cd build-cmake
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . -j8
        cd ..
